Manager:
    HomeScreen:
    FirstScreen:


<HomeScreen>:
    name :'Home'
    Button:
        text :'To do list'
        on_release:
            app.root.current = 'First'
            root.manager.transition.direction ='left'

<FirstScreen>:
    name:'First'
    Button:
        text : 'Back'
        on_release:
            app.root.current = 'Home'
            root.manager.transition.direction ='right'